// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR_pdeJgvBJ3o4IWSpe4_t5AN-fMGI94U',
    appId: '1:53065452799:web:4a6f6546d50a812a5690ca',
    messagingSenderId: '53065452799',
    projectId: 'loginui-f37f4',
    authDomain: 'loginui-f37f4.firebaseapp.com',
    storageBucket: 'loginui-f37f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh5Xl7NZxTYxxrKb4O1H2Kssdz9VFtX4s',
    appId: '1:53065452799:android:3c5aeae344204ba25690ca',
    messagingSenderId: '53065452799',
    projectId: 'loginui-f37f4',
    storageBucket: 'loginui-f37f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRZgSs24bimZ3fJwJhTVLM1JHzHAjdOM',
    appId: '1:53065452799:ios:a29267f280dbb79a5690ca',
    messagingSenderId: '53065452799',
    projectId: 'loginui-f37f4',
    storageBucket: 'loginui-f37f4.appspot.com',
    iosClientId: '53065452799-9nimukr1dltfe51u4rguk6k5o0ds2dn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXRZgSs24bimZ3fJwJhTVLM1JHzHAjdOM',
    appId: '1:53065452799:ios:a29267f280dbb79a5690ca',
    messagingSenderId: '53065452799',
    projectId: 'loginui-f37f4',
    storageBucket: 'loginui-f37f4.appspot.com',
    iosClientId: '53065452799-9nimukr1dltfe51u4rguk6k5o0ds2dn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginui',
  );
}
